name: Deploy To itch.io

on:
  push:
    branches: [ main ]

jobs:
  deploy_to_itch:
    runs-on: windows-2019
    env:
      NODE_ENV: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.8'
          cache: 'yarn'

      - name: Setup Environment
        shell: bash
        run: make install
        
      - name: Build and Zip the Game
        shell: bash
        run: make release

      - name: Butler Push
        shell: bash
        run: make butler-deploy
        env: 
          BUTLER_API_KEY: ${{ secrets.BUTLER_CREDENTIALS }}
